$name = "Peba";
echo "<p> My name is $name</p>";
$string1 = "<p>This is the first part ";
$string2 = "of a sentence</p>";
echo $string1.$string2;
$myNumber = 45;
$calc = $myNumber +31 / 97 + 4;
echo "The result of the calculation is ".$calc;
$myBool = true;
echo "<p>This statemant is true. Display:".$myBool."</p>";
$myBool = false;
echo "<p>This statemant is false. Display nothing:".$myBool."</p>";
$variableName = "name";
echo $$variableName;